"use client";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { useLang } from "@/context/LanguageContext";
import { industriesByLang, pageCopy, getService } from "@/lib/marketing-content";
import PageShell from "@/components/marketing/PageShell";
import MarketingHero from "@/components/marketing/MarketingHero";
import Container from "@/components/ui/Container";
export default function IndustriesHub(){ const {lang}=useLang(); const copy=pageCopy[lang].industries; const items=industriesByLang[lang]; return <PageShell><MarketingHero eyebrow={copy.eyebrow} title={copy.title} description={copy.description} primaryHref="/contact" primaryLabel={lang==="en"?"Discuss Your Business":"Hablemos de su negocio"}/><section className="py-20"><Container><div className="grid gap-6 md:grid-cols-2">{items.map((industry)=><article key={industry.slug} id={industry.slug} className="rounded-2xl border border-[rgba(14,165,233,.14)] bg-vx-bg2 p-7"><h2 className="text-2xl font-semibold">{industry.title}</h2><p className="mt-4 text-vx-muted">{industry.summary}</p><div className="mt-6 grid gap-6 sm:grid-cols-2"><div><h3 className="font-semibold text-vx-silver">{lang==="en"?"Common challenges":"Desafíos comunes"}</h3><ul className="mt-3 space-y-2 text-sm text-vx-muted">{industry.challenges.map(x=><li key={x}>• {x}</li>)}</ul></div><div><h3 className="font-semibold text-vx-silver">{lang==="en"?"Useful solutions":"Soluciones útiles"}</h3><ul className="mt-3 space-y-2 text-sm text-vx-muted">{industry.solutions.map(x=><li key={x}>• {x}</li>)}</ul></div></div><div className="mt-7 flex flex-wrap gap-2">{industry.recommended.map(slug=>{const s=getService(lang,slug); return s?<Link key={slug} href={`/services/${slug}`} className="inline-flex items-center gap-1 rounded-full border border-[rgba(14,165,233,.2)] px-3 py-1.5 text-xs text-vx-cyan">{s.shortTitle}<ArrowRight size={12}/></Link>:null})}</div></article>)}</div></Container></section></PageShell> }
